import React, { useState } from 'react';
import { motion } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { Download, CheckCheck, FileText, AlignLeft, User, Calendar, CheckSquare, Scale, AlertCircle, FileDown } from 'lucide-react';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { saveAs } from "file-saver";


const ResultDisplay = ({ result, transcript, detectedLanguage }) => {
    const [activeTab, setActiveTab] = useState('summary'); // 'summary' or 'transcript'

    const downloadText = (content, filename) => {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    // Helper to separate sections (Reused for Docx)
    const parseSections = (md) => {
        if (!md) return [];
        const sections = [];
        const lines = md.split('\n');
        let currentSection = { title: "Introduction", content: [] };

        lines.forEach(line => {
            if (line.startsWith('# ')) {
                if (currentSection.content.length > 0 || currentSection.title !== "Introduction") {
                    sections.push(currentSection);
                }
                currentSection = { title: line.replace('# ', '').trim(), content: [], isTitle: true };
            }
            else if (line.startsWith('## ')) {
                if (currentSection.content.length > 0 || currentSection.title !== "Introduction") {
                    sections.push(currentSection);
                }
                currentSection = { title: line.replace('## ', '').trim(), content: [] };
            } else {
                currentSection.content.push(line);
            }
        });
        if (currentSection.content.length > 0 || currentSection.title) {
            sections.push(currentSection);
        }
        return sections;
    };

    const parsedSections = activeTab === 'summary' ? parseSections(result) : null;

    const exportDocx = () => {
        const sectionsToExport = parseSections(result); // Always parse result
        if (!sectionsToExport.length) return;

        const docChildren = sectionsToExport.flatMap(section => {
            const heading = new Paragraph({
                text: section.title,
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 200 },
            });

            const contentParagraphs = section.content.map(line => {
                // Basic bullet handling
                if (line.trim().startsWith('*')) {
                    return new Paragraph({
                        text: line.replace('*', '').trim(),
                        bullet: { level: 0 }
                    });
                }
                return new Paragraph({
                    text: line
                });
            });

            return [heading, ...contentParagraphs];
        });

        const doc = new Document({
            sections: [{
                properties: {},
                children: [
                    new Paragraph({
                        text: "Meeting Minutes (Generated by MeetLyze)",
                        heading: HeadingLevel.TITLE,
                        spacing: { after: 400 }
                    }),
                    ...docChildren
                ]
            }]
        });

        Packer.toBlob(doc).then(blob => {
            saveAs(blob, "meeting_minutes.docx");
        });
    };

    const renderSectionContent = (section) => {
        const contentStr = section.content.join('\n');

        // Custom Renderer for "Speaker Timeline"
        if (section.title.toLowerCase().includes("speaker timeline") || section.title.toLowerCase().includes("timeline")) {
            const timelineItems = section.content.filter(l => l.trim().startsWith('*')).map(l => {
                const match = l.match(/\* \[(.*?)\] (.*?): (.*)/);
                if (match) {
                    return { time: match[1], speaker: match[2], text: match[3] };
                }
                // Fallback for different formats
                return { text: l.replace('* ', '') };
            });

            if (timelineItems.length > 0 && timelineItems[0].time) {
                return (
                    <div className="space-y-4 font-sans">
                        {timelineItems.map((item, idx) => (
                            <div key={idx} className="flex gap-4 group">
                                <div className="flex flex-col items-center">
                                    <div className="w-16 px-2 py-1 bg-zinc-500/20 rounded text-xs font-mono text-zinc-300 text-center whitespace-nowrap">
                                        {item.time}
                                    </div>
                                    {idx !== timelineItems.length - 1 && <div className="w-0.5 min-h-[20px] bg-white/10 flex-1 my-2 group-hover:bg-zinc-500/20 transition-colors" />}
                                </div>
                                <div className="pb-4">
                                    <div className="flex items-center gap-2 mb-1">
                                        <User className="w-3 h-3 text-zinc-400" />
                                        <span className="text-sm font-semibold text-zinc-300">{item.speaker}</span>
                                    </div>
                                    <p className="text-white/80 text-sm leading-relaxed">{item.text}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                );
            }
        }

        // Custom Renderer for "Action Items"
        if (section.title.toLowerCase().includes("action item")) {
            const items = section.content.filter(l => l.trim().startsWith('*')).map(l => {
                // Try to parse Owner and Deadline if format matches: * Task - Owner (Deadline: Date)
                // Or simple: * Task
                return l.replace('* ', '');
            });

            return (
                <div className="space-y-3">
                    {items.map((item, idx) => (
                        <div key={idx} className="flex items-start gap-3 bg-zinc-500/5 border border-zinc-500/20 p-3 rounded-lg hover:bg-zinc-500/10 transition-colors">
                            <CheckSquare className="w-5 h-5 text-zinc-400 mt-0.5 shrink-0" />
                            <span className="text-white/90 text-sm">{item}</span>
                        </div>
                    ))}
                </div>
            )
        }

        // Custom Renderer for "Decisions Made"
        if (section.title.toLowerCase().includes("decision")) {
            const decisions = section.content.filter(l => l.trim().startsWith('*')).map(l => l.replace('* ', ''));
            if (decisions.length > 0) {
                return (
                    <div className="space-y-3">
                        {decisions.map((decision, idx) => (
                            <div key={idx} className="flex items-start gap-3 bg-emerald-500/5 border border-emerald-500/20 p-4 rounded-xl">
                                <Scale className="w-5 h-5 text-emerald-400 mt-0.5 shrink-0" />
                                <span className="text-white/90 text-sm leading-relaxed">{decision}</span>
                            </div>
                        ))}
                    </div>
                );
            }
        }

        // Custom Renderer for "Sentiment Summary"
        if (section.title.toLowerCase().includes("sentiment")) {
            return (
                <div className="bg-gradient-to-br from-pink-500/10 to-rose-500/5 border border-pink-500/20 p-6 rounded-2xl relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-24 h-24 bg-pink-500/10 rounded-full blur-2xl -mr-12 -mt-12" />
                    <p className="text-pink-100/90 leading-relaxed italic relative z-10">
                        "{section.content.join(' ')}"
                    </p>
                </div>
            );
        }

        // Custom Renderer for "Priority Tasks"
        if (section.title.toLowerCase().includes("priority")) {
            const tasks = section.content.filter(l => l.trim().startsWith('*')).map(l => l.replace('*', '').trim());
            if (tasks.length > 0) {
                return (
                    <div className="grid gap-3">
                        {tasks.map((task, idx) => (
                            <div key={idx} className="flex items-center gap-3 bg-amber-500/5 border border-amber-500/20 px-4 py-3 rounded-lg">
                                <AlertCircle className="w-4 h-4 text-amber-400 shrink-0" />
                                <span className="text-amber-100/90 text-sm font-medium">{task}</span>
                            </div>
                        ))}
                    </div>
                );
            }
        }

        // Default Markdown
        return (
            <div className="prose prose-invert prose-sm max-w-none text-white/80 leading-relaxed">
                <ReactMarkdown>{contentStr}</ReactMarkdown>
            </div>
        );
    };

    const [reportSent, setReportSent] = useState(false);

    if (!result) return null;

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full max-w-4xl mx-auto mt-8"
        >
            <div className="bg-zinc-950 border border-white/10 rounded-2xl shadow-2xl relative overflow-hidden flex flex-col min-h-[700px]">
                {/* Header */}
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-zinc-500 via-white to-zinc-700" />

                <div className="p-6 border-b border-white/10 flex flex-col md:flex-row justify-between items-center gap-4 bg-white/5">
                    <div className="flex flex-col">
                        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                            <CheckCheck className="w-6 h-6 text-green-400" />
                            Meeting Results
                        </h2>
                        {detectedLanguage && (
                            <div className="flex items-center gap-4 mt-2">
                                <span className="text-xs text-white/50 font-mono bg-white/5 px-2 py-1 rounded">
                                    Detected: <span className="text-zinc-300 font-semibold">{detectedLanguage}</span>
                                </span>
                                {!reportSent ? (
                                    <button
                                        onClick={() => { setReportSent(true); setTimeout(() => setReportSent(false), 3000); }}
                                        className="text-[10px] text-white/30 hover:text-red-400 transition-colors flex items-center gap-1"
                                    >
                                        <AlertCircle className="w-3 h-3" /> Report Incorrect
                                    </button>
                                ) : (
                                    <span className="text-[10px] text-green-400 flex items-center gap-1">
                                        <CheckCheck className="w-3 h-3" /> Feedback Sent
                                    </span>
                                )}
                            </div>
                        )}
                    </div>
                    <div className="flex gap-2">
                        <button
                            onClick={exportDocx}
                            className="flex items-center gap-2 px-4 py-2 bg-blue-600/20 hover:bg-blue-600/30 text-blue-300 rounded-lg transition-colors border border-blue-500/30 text-xs font-medium uppercase tracking-wider"
                        >
                            <FileDown className="w-4 h-4" />
                            DOCX
                        </button>
                        <button
                            onClick={() => window.print()}
                            className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/80 transition-colors border border-white/10 text-xs font-medium uppercase tracking-wider"
                        >
                            <FileText className="w-4 h-4" />
                            PDF
                        </button>
                        <button
                            onClick={() => downloadText(result, 'meeting_summary.md')}
                            className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/80 transition-colors border border-white/10 text-xs font-medium uppercase tracking-wider"
                        >
                            <Download className="w-4 h-4" />
                            MD
                        </button>
                    </div>
                </div>

                {/* Tabs */}
                <div className="flex border-b border-white/10 bg-black/20">
                    <button
                        onClick={() => setActiveTab('summary')}
                        className={`flex-1 py-4 text-sm font-medium transition-colors flex items-center justify-center gap-2 relative
                            ${activeTab === 'summary'
                                ? 'text-white bg-white/5'
                                : 'text-white/50 hover:text-white/80 hover:bg-white/5'}`}
                    >
                        <AlignLeft className="w-4 h-4" />
                        AI Insights
                        {activeTab === 'summary' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-zinc-400" />}
                    </button>
                    <button
                        onClick={() => setActiveTab('transcript')}
                        className={`flex-1 py-4 text-sm font-medium transition-colors flex items-center justify-center gap-2 relative
                            ${activeTab === 'transcript'
                                ? 'text-white bg-white/5'
                                : 'text-white/50 hover:text-white/80 hover:bg-white/5'}`}
                    >
                        <FileText className="w-4 h-4" />
                        Raw Transcript
                        {activeTab === 'transcript' && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-zinc-400" />}
                    </button>
                </div>

                {/* Content */}
                <div className="p-8 overflow-y-auto flex-1 h-[600px] custom-scrollbar bg-zinc-950">
                    {activeTab === 'summary' ? (
                        <div className="space-y-8 max-w-4xl mx-auto">
                            {parsedSections.map((section, idx) => (
                                section.content.length > 0 && (
                                    <motion.div
                                        key={idx}
                                        initial={{ opacity: 0, y: 10 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        transition={{ delay: idx * 0.1 }}
                                        className={section.isTitle ? 'text-center mb-8' : ''}
                                    >
                                        {!section.isTitle && (
                                            <h3 className="font-bold mb-4 text-sm uppercase tracking-widest text-zinc-400 border-b border-white/10 pb-2">
                                                {section.title}
                                            </h3>
                                        )}
                                        {section.isTitle && (
                                            <h1 className="text-3xl md:text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60 mb-2">
                                                {section.title}
                                            </h1>
                                        )}
                                        {renderSectionContent(section)}
                                    </motion.div>
                                )
                            ))}

                            {parsedSections.length === 0 && (
                                <div className="prose prose-invert prose-lg max-w-none text-center pt-20 text-white/30">
                                    <p>No structured insights found. Displaying raw output:</p>
                                    <div className="text-left mt-8 p-6 bg-white/5 rounded-xl text-white/80">
                                        <ReactMarkdown>{result}</ReactMarkdown>
                                    </div>
                                </div>
                            )}
                        </div>
                    ) : (
                        <div className="font-mono text-sm text-white/60 whitespace-pre-wrap leading-loose max-w-4xl mx-auto">
                            {transcript || "No transcript available."}
                        </div>
                    )}
                </div>

                {/* Footer Badge */}
                <div className="p-4 border-t border-white/5 bg-black/40 flex justify-center items-center gap-2">
                    <span className="text-[10px] text-white/20 uppercase tracking-[0.2em]">Powered by</span>
                    <div className="flex items-center gap-1.5 opacity-40 grayscale hover:grayscale-0 hover:opacity-80 transition-all cursor-default">
                        <div className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                        <span className="text-[10px] font-bold text-white tracking-widest">GEMINI 2.0 FLASH</span>
                    </div>
                </div>
            </div>
        </motion.div >
    );
};

export default ResultDisplay;
